image: registry.znuny.com/znuny/docker-otrs6ci:latest

stages:
  - test
  - deploy

job_unit_otrs_Znuny4OTRSCustomerMap:
  stage: test
  services:
    - name: docker.io/elgalu/selenium:latest
    - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
      alias: mysql
  script:
    - env
    - pwd
    - /run.sh
    - su -c "bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-CustomerMap.sopm" - otrs
    - su -c "bin/otrs.Console.pl Admin::Config::Update --setting-name Znuny4OTRS::CustomerMap::GoogleAPIKey --value $GOOGLE_APIKEY" - otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSCustomerMap/Selenium/Agent/Znuny4OTRSAgentCustomerMap" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSCustomerMap/System/GMaps" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSCustomerMap/System/GMapsCustomer" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSCustomerMap/var/packagesetup/Znuny4OTRSCustomerMap" -s /bin/bash otrs

job_deploy_otrs_Znuny4OTRSCustomerMap:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-CustomerMap.git
