image: registry.znuny.com/znuny/internal/docker-znuny-ci:6.2.2

include:
  - project: 'Znuny/Internal/Znuny'
    file: '/templates/gitlab/default/default.yml'

default:
  before_script:
    - /run.sh

