image: registry.znuny.com/znuny/internal/docker-otrs6ci:$OTRS_TAG

include:
  - project: 'Znuny/Internal/Znuny'
    file: '/templates/gitlab/default/default.yml'

default:
  before_script:
    - /run.sh
    
