image: registry.znuny.com/znuny/internal/docker-otrs6ci:$OTRS_TAG

include:
  - project: 'Znuny/Internal/Znuny'
    file: '/templates/gitlab/default/.gitlab-ci-default.yml'

default:
  before_script:
    - /run.sh
    - env
    - su -c "/opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/$CI_PROJECT_NAME.sopm" - otrs